### PR TITLE
Support Unified serial PCAPs + Fix for OFW 0.98

### PR DESCRIPTION
**Pull request by WillyJL**
Counterpart support to https://github.com/justcallmekoko/ESP32Marauder/pull/452, more info there

### CODE REVIEW

**Comment by WillyJL** [comment]
Looks like koko plans on merging the feature into marauder, so should just be a matter of time now as he tests.

Also, OFW refactored serial and UART stuff, I'll add that to this PR aswell soontm

**Comment by WillyJL** [comment]
there we go, now compatible with OFW dev branch changes, also added remember 5v so it doesnt turn off after closing the app if it was enabled before

and bumbed to version 7.0, considering this changes significantly how pcaps are done i felt like a major version bump was appropriate, can revert if you dont think so

**Comment by WillyJL** [comment]
also koko merged the PR into marauder, but on a separate branch. what happened with a recent pr for nmea gps tells me that eventually he will merge that into develop branch and release later on, so still might take a little.

**Comment by 0xchocolate** [comment]
Yes, I was going to ask you to set the version. :) Thanks!

**Comment by WillyJL** [comment]
Right, there's also new changes with "expansion modules". Will port those fixes here too soontm

**Comment by 0xchocolate** [comment]
Some of the parsing logic could probably be refactored later, but if it works, it works! Merging now.

**Pull request merged**
